Created CSS
INF6420/ss22-hd5420 pull request #4
Opened 2022-06-17 17:35 UTC by hd5420

2022-06-18 14:10 UTC, axamei requested changes
Please add alt text to your logo images on all HTML pages and make sure you are not skipping heading levels.

2022-06-18 14:10 UTC, axamei commented on about.html
> +        <img src="images/twitter.png" class="tw">
The logos need alternative text. Add `alt` attribute to each img

2022-06-18 14:10 UTC, axamei commented on about.html
> +<h3>
A heading level was skipped. You went from `h1` to `h3`. Think of headings like a table of contents for the page content. If you are trying to style the list to have a certain font size, use CSS properties like `font-size`.

2022-06-18 14:10 UTC, axamei commented on connect.html
>     <h2>Where to Find Me</h2>
You are missing an `h1` on this page.

2022-06-18 14:10 UTC, axamei commented on index.html
> +    <h2 id="section-title">Introduction</h2>
You are missing an `h1` on this page

2022-06-22 22:24 UTC, hd5420 commented
Hi @axamei I fixed these last week and submitted a pull request. I hope I didn't mess up again! :) Thanks!! ~Angie

2022-06-23 01:23 UTC, axamei approved these changes
👍

2022-06-23 01:23 UTC, merged

2022-06-23 01:24 UTC, axamei commented
Hi @hd5420 I merged this work into the main branch. Book an appointment if you would like a quick walkthrough of the next steps

2022-06-24 00:25 UTC, hd5420 commented
Thank you! I'll see you in the morning!